meta:
  engine: 4.1.0
  version: 0.0.2
  author: auryn

units: 
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
  kcow: 14
  kcoh: 14

points:
    key.padding: ky
    zones:
        main:
            rows:
                bottom.row_net: P2
                home.row_net: P0
                top.row_net: P1
            columns:
                pinky:
                    key:
                        col_net: P7
                        spread: kx
                ring:
                    key:
                        col_net: P6
                        stagger: 0.4 ky
                        spread: kx
                middle:
                    key:
                        col_net: P5
                        stagger: 0.28 ky
                        spread: kx
                index:
                    key:
                        col_net: P4
                        stagger: -0.33 ky
                        spread: kx
                inner:
                    key:
                        col_net: P3
                        stagger: -0.11 ky 
                        spread: kx
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [-0.5 kx, -1.15 ky]
            rows.home.row_net: P8
            columns:
                inner.key:
                    origin: [-1 kx, -1.15 ky]
                    col_net: P5
                    spread: kx
                home.key:
                    col_net: P4
                    splay: -0.5 ky
                    origin: [-0.5 kx, -0.15 ky]
                    spread: 1.05 kx
                outer.key:
                    col_net: P3
                    spread: 1.05 kx
                    splay: -0.5 ky 
                    origin: [-0.52 ky, -0.2 kx]
        mountscrew_top_left:
          anchor:
            ref.aggregate.parts:
              [main_pinky_top, main_ring_top, main_ring_home]
            shift: [-2.5, -0.5]
          columns.screw.key.tags: [screw]
        mountscrew_bottom_left:
          anchor:
            ref.aggregate.parts:
              [main_pinky_home, main_ring_home, main_ring_bottom]
            shift: [-2.5, -0.5]
          columns.screw.key.tags: [screw]
        mountscrew_top_right:
          anchor:
            ref.aggregate.parts:
              [main_index_top, main_index_home, main_inner_top, main_inner_home]
            shift: [0, 0]
          columns.screw.key.tags: [screw]
        mountscrew_bottom_right:
          anchor:
            ref.aggregate.parts:
              [main_index_home, main_index_bottom, main_inner_home, main_inner_bottom]
            shift: [0, 0]
          columns.screw.key.tags: [screw]
        mountscrew_right_right:
          anchor:
            ref.aggregate.parts:
              [thumb_home_home, thumb_outer_home]
            shift: [0, 0]
          columns.screw.key.tags: [screw]
outlines:
    _base: 
        - what: rectangle
          bound: true
          where: 
            - /main/
            - /thumb/
          size: [kx, ky]
    _switch_cutouts:
      - what: rectangle
        where: 
          - /main/
          - /thumb/
        size: [kcow, kcoh]
    _board_outline:
        -   what: polygon
            fillet: 2
            points:
                -   ref: thumb_outer_home
                    shift: [0.6kx, 0.6ky]
                -   ref: thumb_outer_home
                    shift: [0.6kx, -0.6ky]
                -   ref: thumb_outer_home
                    shift: [-0.4kx, -0.6ky]

                -   ref: thumb_home_home
                    shift: [0.4kx, -0.6ky]
                -   ref: thumb_home_home
                    shift: [-0.4kx, -0.6ky]

                -   ref: thumb_inner_home
                    shift: [0.4kx, -0.6ky]
                -   ref: thumb_inner_home
                    shift: [-0.6kx, -0.6ky]
                -   ref: thumb_inner_home
                    shift: [-0.6kx, 0.65ky]

                -   ref: main_index_bottom
                    shift: [-0.6kx, -0.6ky]

                -   ref: main_middle_bottom
                    shift: [0.4kx, -0.6ky]
                -   ref: main_middle_bottom
                    shift: [-0.4kx, -0.6ky]

                -   ref: main_ring_bottom
                    shift: [0.6kx, -0.6ky]
                -   ref: main_ring_bottom
                    shift: [-0.4kx, -0.6ky]

                -   ref: main_pinky_bottom
                    shift: [0.6kx, -0.6ky]
                -   ref: main_pinky_bottom
                    shift: [0.6kx, -0.6ky]
                -   ref: main_pinky_bottom
                    shift: [-0.6kx, -0.6ky]
                

                -   ref: main_pinky_top
                    shift: [-0.6kx, 0.6ky]
                -   ref: main_pinky_top
                    shift: [0.4kx, 0.6ky]

                -   ref: main_ring_top
                    shift: [-0.6kx, 0.6ky]
                -   ref: main_ring_top
                    shift: [0.4kx, 0.6ky]

                -   ref: main_middle_top
                    shift: [-0.6kx, 0.6ky]
                -   ref: main_middle_top
                    shift: [0.6kx, 0.6ky]

                -   ref: main_index_top
                    shift: [-0.4kx, 0.6ky]
                -   ref: main_index_top
                    shift: [0.5kx, 0.6ky]

                -   ref: main_inner_top
                    shift: [-0.4kx, 0.6ky]
                -   ref: main_inner_top
                    shift: [0.5kx, 0.6ky]

                -   ref: main_inner_top
                    shift: [0.6kx, 0.4ky]
                -   ref: main_inner_top
                    shift: [1.8kx, 0.4ky]

                -   ref: main_inner_bottom
                    shift: [1.8kx, -0.9ky]
    _keycap_outlines:
          - what: outline
            name: _base
            fillet: 2
    _switch_plate:
        - what: outline
          name: _base
        - what: polygon
          operation: add
          points:
            - ref: thumb_home_home
              shift: [0.5kx, 0.5 ky]
            - ref: thumb_outer_home
              shift: [-0.5kx, 0.5 ky]
            - ref: thumb_outer_home
              shift: [0, 0]
        - what: polygon
          operation: add
          points:
            - ref: main_inner_bottom 
              shift: [0.5 kx, -0.5 ky]
            - ref: main_inner_bottom 
              shift: [0.5 kx, -1 ky]
            - ref: main_inner_bottom 
              shift: [-0.2 kx, -0.5 ky]
        - what: polygon
          operation: add
          points:
            - ref: main_index_bottom 
              shift: [0, 0]
            - ref: thumb_inner_home
              shift: [-0.5 kx, -0.5 ky]
            - ref: thumb_home_home
              shift: [-0.5 kx, -0.5 ky]
        - what: outline
          name: _switch_plate
          expand: 2
          fillet: 2
        - what: outline
          name: _switch_cutouts
          operation: subtract

cases.avocado:
    -   what: outline
        name: _board_outline
        extrude: 3
        operation: subtract
    -   what: outline
        name: _keycap_outlines
        extrude: 6
        operation: add
pcbs:
  switch_plate:
    outlines:
      main.outline: _switch_plate
    footprints:
      screws:
        what: mounting_hole
        params:
          drill: 4.3
          outline: 0.4
        where: [screw]
      front_text: &text
          what: text
          where: &textWhere
              ref: 
                - main_index_bottom
              shift: [-7, -0.6 cx]
          params: &textParams
              text: MX Switch Plate
              justify: left
      back_text:
          <<: *text
          where:
              <<: *textWhere
              shift: [7, -0.6 cx]
          params:
              <<: *textParams
              layer: B.SilkS
              justify: left mirror
      
  bottom_case:
    outlines:
      main.outline: _board_outline
    footprints:
      screws:
        what: mounting_hole
        params:
        where: [screw]
      front_text: &text
          what: text
          where: &textWhere
              ref: 
                - main_pinky_bottom
              shift: [-7, -0.4 cx]
          params: &textParams
              text: Avocado v0.2\nA keyboard for Auryn
              justify: left
      back_text:
          <<: *text
          where:
              <<: *textWhere
              shift: [7, -0.4 cx]
          params:
              <<: *textParams
              layer: B.SilkS
              justify: left mirror
      avocado_image:
         where:
           ref: main_index_top
           shift: [-12, -4]
         params:
           scale: 0.05
         what: avocado
      
  keyboard_pcb:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        diode:
            what: sod-123w
            where:
              - /main/
              - /thumb/
            params:
                from: "{{row_net}}"
                to: "{{row_net}}"
            adjust:
                shift: [ -7.6, -1.6 ]
                rotate: 90
        switches:
            what: choc
            where: 
              - /main/
              - /thumb/
            params:
                keycaps: true
                reverse: true
                hotswap: true
                from: "{{col_net}}"
                to: "{{row_net}}"
        promicro:
            what: promicro_pretty
            where:
                ref: 
                  - main_inner_home
                shift: [22, 4.5]
            params:
              reversable_pins: 13
                # rotate: -90
        battery_connector:
            what: jst-s2b-ph-kl
            where:
                ref:
                  - main_inner_bottom
                shift: [24, -7]
                rotate: 180
            params:
                neg: B-
                pos: pos
        on_off_switch:
            what: pcm12
            where:
                ref: 
                  - main_inner_bottom
                shift: [30, -2]
                rotate: 90
            params:
                from: pos
                to: B+
        reset_switch:
            what: reset_switch
            where:
                ref: 
                  - main_inner_bottom
                shift: [30, -10.5]
                rotate: 90
            params:
                r1: RST
                r2: GND
        # front_text: &text
        #     what: text
        #     where: &textWhere
        #         ref: 
        #           - main_pinky_bottom
        #         shift: [12, -7]
        #     params: &textParams
        #         text: Avocado\nA keyboard from Auryn
        #         justify: left
        # back_text:
        #     <<: *text
        #     where:
        #         <<: *textWhere
        #         shift: [27, -7]
        #     params:
        #         <<: *textParams
        #         layer: B.SilkS
        #         justify: left mirror
        screws:
          what: mounting_hole
          params:
          where: [screw]
