file_format: "1"
id: tofu
name: Tofu
type: shield
url: https://github.com/auryn31/avocado
requires: [pro_micro]
exposes: [i2c_oled]
features:
    - keys
    - display
siblings:
    - avocado_left
    - avocado_right
