CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_DISPLAY=y
CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_ZMK_DISPLAY_STATUS=y
CONFIG_ZMK_DISPLAY_STATUS_BATTERY=y
CONFIG_ZMK_DISPLAY_STATUS_LAYERS=y

# Reduce display refresh rate to prevent interference
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=2048
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5

# Debug
CONFIG_LOG=y
CONFIG_LOG_MAX_LEVEL=4
CONFIG_ZMK_USB_LOGGING=y
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_SSD1306_LOG_LEVEL_DBG=y
