file_format: "1"
id: avocado
name: Avocado
type: shield
url: https://github.com/Narkoleptika/josukey/
requires: [pro_micro]
exposes: 
  - i2c_oled
features:
    - keys
    - display
siblings:
    - avocado_left
    - avocado_right
